version: "2"

services:
  sonatype:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    environment:
      - NEXUS_CONTEXT=nexus
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:
